### ISSUE TITLE
Project TODO item doesn't get deleted upon user request

### ISSUE THREAD

**Issue by ablekh** [hubzero/hubzero-cms#145]
A project TODO item does not get physically deleted upon user's confirmation in the "Permanently delete this item?" dialog box. A brief review of the relevant code ("core/plugins/projects/todo/todo.php") reveals that the call on line 718
```
if (!$objTD->deleteTodo($this->model->get('id'), $todoid))
```
does not actually process the user's input in the relevant dialog box (which is the 3rd argument in `deleteTodo()`, where the default value of the 3rd parameter (`0`) is to not physically delete an item).

**Comment by zooley** [comment]
I believe this is functioning as intended. Items are very rarely _truly_ deleted from the CMS when using the front-end; True deletion is largely reserved for administrative functions. For all intensive purposes, the end user knows no difference. This is all done by design so accidentally removed content (or, should a user's account get compromised, any maliciously "deleted" content) can be easily restored.

In any case, the wording has been altered to remove 'permanently'.
