### ISSUE TITLE
No `yum` packages?

### ISSUE THREAD

**Issue by ajs6f** [hubzero/hubzero-cms#192]
https://hubzero.org/services/opensource advertises that

> It is now possible to install HUBzero on RedHat Enterprise Linux 6. 

but the link provided is to a [blank page](https://help.hubzero.org/documentation/210/installationrh). Are there in fact `yum` packages available, and if not, how can I go about testing HUBzero on a Centos machine? Thanks for any advice!

**Comment by nkissebe** [comment]
You need to go one more level down on the menu to the left which takes you to https://help.hubzero.org/documentation/210/installationrh/installrh

The installation should work for RedHat 6.x, it currently will not work for CentOS due to some unfortunate choices in how the distribution name is checked and used in some packages. This will eventually be fixed.

**Comment by ajs6f** [comment]
Thanks! Do you have an ETA for CentOS-compatible packages? Do you have a good list of places where scripts are relying on distro name? (I might be able to spend some time making PRs.)

**Comment by ajs6f** [comment]
Also, is there some documentation on how to install from source?

**Comment by nkissebe** [comment]
HUBzero 2.2 packages are CentOS 6 compatible now, although we use RedHat in production so there has been limited testing. Full installation is only possible via packages. Closing issue.
